In [1]:
import torch

In [3]:
torch.linspace(1, 0.5, 10)

tensor([1.0000, 0.9444, 0.8889, 0.8333, 0.7778, 0.7222, 0.6667, 0.6111, 0.5556,
        0.5000])

In [6]:
torch.distributions.bernoulli.Bernoulli(torch.Tensor([0.345])).sample()

tensor([0.])

In [23]:
from gmlp import gMLP
network = gMLP(128, 768, 224, 1) # 输入应该为（..., seq_len, d_model）

In [24]:
network.train()

gMLP(
  (blocks): ModuleList(
    (0): GatingMlpBlock(
      (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (proj_1): Linear(in_features=256, out_features=768, bias=True)
      (activation): GELU(approximate='none')
      (spatial_gating_unit): SpatialGatingUnit(
        (norm): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
        (proj): Linear(in_features=224, out_features=224, bias=True)
      )
      (proj_2): Linear(in_features=384, out_features=256, bias=True)
    )
  )
)

In [35]:
x = torch.rand((2, 48, 48, 48, 96))

In [39]:
x = x.permute(0,4,1,2,3)
x.shape

torch.Size([2, 96, 48, 48, 48])

In [36]:
from torch import nn
conv3d = nn.Conv3d(96,96,1,1)
print(conv3d(x).shape)

RuntimeError: Given groups=1, weight of size [96, 96, 1, 1, 1], expected input[2, 48, 48, 48, 96] to have 96 channels, but got 48 channels instead

In [28]:
output = network(x)

RuntimeError: Given normalized_shape=[256], expected input with shape [*, 256], but got input of size[2, 1, 3, 224, 128]

In [22]:
output.shape

torch.Size([3, 224, 128])

In [31]:
N, C, H, W, D = 20, 5, 10, 10, 10
input = torch.randn(N, C, H, W, D)
import torch.nn as nn
layer_norm = nn.LayerNorm(D)
output = layer_norm(input)

In [30]:
output.shape

torch.Size([20, 5, 10, 10, 10])

In [14]:
import torch
import torch.nn as nn
m = nn.Dropout(p=0)
input = torch.randn(4, 5)
print(input)
output = m(input)
print(output)

tensor([[-0.1941, -0.7038,  0.9454, -0.0071,  0.1688],
        [ 1.7001, -1.7497, -0.0635,  0.5015,  0.9188],
        [ 0.8641,  0.2390,  2.1837,  0.2790, -0.7592],
        [-0.8017,  0.6523,  1.0473,  0.9581,  0.5761]])
tensor([[-0.1941, -0.7038,  0.9454, -0.0071,  0.1688],
        [ 1.7001, -1.7497, -0.0635,  0.5015,  0.9188],
        [ 0.8641,  0.2390,  2.1837,  0.2790, -0.7592],
        [-0.8017,  0.6523,  1.0473,  0.9581,  0.5761]])
